default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Example1_development

test:
  <<: *default
  database: Example1_test

production:
  <<: *default
  database: Example1_production
  username: Example1
  password: <%= ENV["EXAMPLE1_DATABASE_PASSWORD"] %>
